export const WEATHER_FETCH = 'WEATHER_FETCH';
export const WEATHER_FETCH_PENDING = 'WEATHER_FETCH_PENDING';
export const WEATHER_FETCH_SUCCESS = 'WEATHER_FETCH_SUCCESS';
export const WEATHER_FETCH_ERROR = 'WEATHER_FETCH_ERROR';

export const WEATHER_SEARCH = 'WEATHER_SEARCH';
export const WEATHER_SEARCH_PENDING = 'WEATHER_SEARCH_PENDING';
export const WEATHER_SEARCH_SUCCESS = 'WEATHER_SEARCH_SUCCESS';
export const WEATHER_SEARCH_ERROR = 'WEATHER_SEARCH_ERROR';

export const UNIT_CHANGE = 'UNIT_CHANGE';

export const CITY_FETCH_SUCCESS = 'CITY_FETCH_SUCCESS';
